<a href="https://colab.research.google.com/github/fd-journey/journey/blob/main/Workshop_Data_Types_figs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Frederic Daoud**
frederic.daoud@gmail.com

#**NOTE:**
Please insert a text cell at the top of the Notebook with your **Full Name** in Bold and your email that you use for *both Journey and Github*

Also, add to the title of the notebook, an underscore as well as your favourite fruit beside it. 

Ex. 'Workshop_Data_Types_Grapes'

#Warm Up

In the cell below, import numpy and name it 'np' and create a list with the data types that were mentioned during a lecture as strings and store the result as "types"
Ex.


```
import ... as ...
types = [...]
```



In [2]:
import numpy as np
types = ["A","3.1","3","True"]


Call the first element in types and slice the last 2 elements in the cell below. Print both results.

In [14]:
print(types[0])
print(types[-2:])


A
['3', 'True']


Divide by 4, the second element in "types" in the code cell below. In the text cell below that, explain why or why not the code was able to execute. (Your explanation does not have to be thorough)

In [17]:
types[1] / 4

TypeError: ignored

Explain here: divide and subtraction operations to not work on string elements. 

#Creating Data Containers

In the cells below, create a list, set, tuple and array. 

The list (in order) should have any 2 numbers as integers, any 2 numbers as floating point numbers and 2 of your favourite music artists as strings. [6 elements total]. Name this list **'First'** and print it. 

The Set (in order) should have 1 even number less than 20 followed by 3 of the first letters of the alphabet as strings in seperate entries. [4 elements total]. Name this set **'Second'** and print it.

The Tuple (in order) should have 6 negative numbers. [6 elements total]. Name this Tuple **'Third'** and print it.

The array (in order) should have the same 6 elements as the tuple but these numbers should be positive. [6 elements total]. Name this array **'Fourth'** and print it.

In [32]:
First = [2,3,3.1,4.6,"Donald Byrd","Lee Burridge"]
print(First)

[2, 3, 3.1, 4.6, 'Donald Byrd', 'Lee Burridge']


In [20]:
Second = {4,"a","b","c"}
print(Second)

{'b', 4, 'c', 'a'}


In [26]:
Third = (-5,-3,-8,-13,-25,-4)
print(Third)


(-5, -3, -8, -13, -25, -4)


In [27]:
import numpy as np
Fourth = np.array(Third) * -1
print(Fourth)

[ 5  3  8 13 25  4]


Add together, the second element of 'First', and the last elements of 'Third' and Fourth.

In [28]:
First[1]+Third[-1]+Fourth[-1]

3

Slice the last 3 elements of 'Fourth' and append them to the list 'First'. Print the result.

In [33]:
First.append(list(Fourth[-3:]))
print(First)

[2, 3, 3.1, 4.6, 'Donald Byrd', 'Lee Burridge', [13, 25, 4]]


Create a 3x3 numpy matrix with 5's on the diagonal and 1's everywhere else and name it 'Matrix'. The matrix should look like this:

$$\begin{bmatrix} 5 & 1 & 1 \\ 1 & 5 & 1 \\ 1 & 1 & 5 \end{bmatrix}$$

In [36]:
x = [[5,1,1],[1,5,1],[1,1,5]]
Matrix = np.array(x)
print(Matrix)

[[5 1 1]
 [1 5 1]
 [1 1 5]]


Call the last element in each row of the matrix.

In [41]:
Matrix[:][2]

array([1, 1, 5])

Create a dictionary with the following keys, 'Name', 'Year', 'Music' and 'Food'. The values associated with each key (in order) should be your name, the current year, you favourite genre of music and one of your favourite foods. Name the dictionary 'Me' and print it. 

In [42]:
Me = {"Name":"Fred", "Year":2021, "Music": "Funk", "Food":"Steak"}
print(Me)

{'Name': 'Fred', 'Year': 2021, 'Music': 'Funk', 'Food': 'Steak'}


Replace the value associated with 'Food' to another one of your favourite foods. Print the updated dictionary.

In [43]:
Me["Food"] = "Pizza"
print(Me)

{'Name': 'Fred', 'Year': 2021, 'Music': 'Funk', 'Food': 'Pizza'}


Create a list with entries 1, 3, 2, 1, 5, 3, 5, 1, 4 and name it 'original'. Create a new list called 'unique' that only contains unique numbers from original.

Example:

```
Input
[1, 2, 3, 1]

Output
[1, 2, 3]
```
**Hint:** Think about the properties of a set from lecture.


In [46]:
original = [1, 3, 2, 1, 5, 3, 5, 1, 4]
unique = list(set(original))
print(unique)

[1, 2, 3, 4, 5]


#Arithmetic Operations

Call the last element of the array "Fourth" that you created above. Raise this element to the second power and add it to the second element of the list "First".

In [47]:
Fourth[-1]**2 + First[1]

19

Add the last three elements of "Third". 

In [48]:
sum(Third[-3:])

-42

Convert the tuple, "Third" to an array, double all the elements in "Third" and add the elements in this array to the elements in "Fourth" using only 1 arithmatic statement. Store this result as "Fifth" and print.

**Hint** Answer should look like this. 


```
Fifth = 2*___(____) + _____
print (Fifth)
```



In [53]:
Fifth = 2 * np.array(Third) + Fourth
print(Fifth)


[ -5  -3  -8 -13 -25  -4]


#Conditionals

Convert "Fifth" to a tuple and use a print statement to see if Fifth is equal to "Third"

In [59]:
print(tuple(Fifth) == Third )

True
